on: [push]

env:
  FILEBROWSER_VERSION: 1.5.0-beta
  DOWNSTREAM: 3

jobs:
  package:
    name: package ${{matrix.dist}} ${{ matrix.arch }}
    runs-on: ${{ matrix.arch }}
    strategy:
      matrix:
        arch: [amd64, arm64]
        dist: [noble]

    steps:
      - uses: actions/checkout@v4
        with:
            persist-credentials: false

      - name: "Launch earthly"
        run: earthly +package --DISTRIBUTION=${{ matrix.dist }} --FILEBROWSER_VERSION=${FILEBROWSER_VERSION} --DOWNSTREAM=${DOWNSTREAM}

      - uses: ${{ vars.deploy }}
        with:
          type: complex
          path: public
          component: main
          key: ${{ secrets.deploy_key }}
